import static com.r3.build.BuildControl.killAllExistingBuildsForJob
@Library('existing-build-control')
import static com.r3.build.BuildControl.killAllExistingBuildsForJob

killAllExistingBuildsForJob(env.JOB_NAME, env.BUILD_NUMBER.toInteger())

pipeline {
    agent {
        dockerfile {
            filename '.ci/Dockerfile'
        }
    }
    options { timestamps() }

    environment {
        EXECUTOR_NUMBER = "${env.EXECUTOR_NUMBER}"
        ARTIFACTORY_CREDENTIALS = credentials('artifactory-credentials')
        CORDA_ARTIFACTORY_USERNAME = "${env.ARTIFACTORY_CREDENTIALS_USR}"
        CORDA_ARTIFACTORY_PASSWORD = "${env.ARTIFACTORY_CREDENTIALS_PSW}"
        CORDA_PUBLISH_REPOSITORY_KEY = "corda-lib"
    }

    stages {
        stage('Tests') {
            steps {
                timeout(60) {
                    sh '''
                    export CORDA_ARTIFACTORY_USERNAME=\"\${ARTIFACTORY_CREDENTIALS_USR}\"
                    export CORDA_ARTIFACTORY_PASSWORD=\"\${ARTIFACTORY_CREDENTIALS_PSW}\"
                    ./gradlew clean test --info
                    '''
                }
            }
            
            post {
                always {
                    junit '**/build/test-results/**/*.xml'
                }
            }
        }

        stage('Deploy') {
            steps {
                sh "./gradlew artifactoryPublish"
            }
        }
    }
    
    post {
        cleanup {
            deleteDir() /* clean up our workspace */
        }
    }

}